import json
import re
from pathlib import Path

import sqlglot
from sqlglot import exp


BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent

SCHEMA_PATH = (
    PROJECT_ROOT
    / "schema_extraction"
    / "schema.json"
)


FORBIDDEN_NODE_TYPES = {
    "insert",
    "update",
    "delete",
    "merge",
    "create",
    "drop",
    "alter",
    "truncate",
    "command",
    "execute",
    "grant",
    "revoke",
    "use",
    "into",
}


def clean_model_output(text):
    """
    Remove Markdown code fences generated by the LLM.

    Example:

    ```sql
    SELECT *
    FROM dbo.Product;
    ```

    becomes:

    SELECT *
    FROM dbo.Product;
    """

    text = text.strip()

    text = re.sub(
        r"^```(?:sql)?\s*",
        "",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"\s*```$",
        "",
        text,
    )

    return text.strip()


def load_schema():
    with SCHEMA_PATH.open(
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def build_schema_lookup(schema_data):
    """
    Build a case-insensitive lookup for tables
    and their columns.

    Example key:
    ("dbo", "product")
    """

    lookup = {}

    for table in schema_data["tables"]:
        schema_name = table["schema"]
        table_name = table["name"]

        key = (
            schema_name.lower(),
            table_name.lower(),
        )

        lookup[key] = {
            "schema": schema_name,
            "table": table_name,
            "columns": {
                column["name"].lower()
                for column in table["columns"]
            },
        }

    return lookup


def resolve_table(
    schema_lookup,
    schema_name,
    table_name,
):
    """
    Find a table in schema.json.

    If schema is omitted, allow the table only
    when its name is unique in the database.
    """

    table_name_lower = table_name.lower()

    if schema_name:
        key = (
            schema_name.lower(),
            table_name_lower,
        )

        return schema_lookup.get(key)

    matches = [
        table_info
        for (
            lookup_schema,
            lookup_table
        ), table_info in schema_lookup.items()
        if lookup_table == table_name_lower
    ]

    if len(matches) == 1:
        return matches[0]

    return None


def validate_sql(sql_text):
    cleaned_sql = clean_model_output(
        sql_text
    )

    result = {
        "valid": False,
        "status": "rejected",
        "cleaned_sql": cleaned_sql,
        "errors": [],
        "referenced_tables": [],
    }

    # -----------------------------------------
    # Empty output
    # -----------------------------------------

    if not cleaned_sql:
        result["errors"].append(
            "SQL is empty."
        )

        return result

    # -----------------------------------------
    # Model abstention
    # -----------------------------------------

    if (
        cleaned_sql.lower()
        == "i do not know"
    ):
        result["status"] = "abstained"

        return result

    # -----------------------------------------
    # Parse as Microsoft T-SQL
    # -----------------------------------------

    try:
        statements = sqlglot.parse(
            cleaned_sql,
            read="tsql",
        )

    except Exception as exc:
        result["errors"].append(
            f"T-SQL parsing failed: {exc}"
        )

        return result

    # -----------------------------------------
    # Exactly one statement
    # -----------------------------------------

    if len(statements) != 1:
        result["errors"].append(
            "Exactly one SQL statement is allowed."
        )

        return result

    statement = statements[0]

    # -----------------------------------------
    # SELECT only
    # -----------------------------------------

    if statement.find(exp.Select) is None:
        result["errors"].append(
            "Only SELECT queries are allowed."
        )

    # -----------------------------------------
    # Block dangerous SQL operations
    # -----------------------------------------

    for node in statement.walk():
        node_type = str(
            getattr(
                node,
                "key",
                node.__class__.__name__,
            )
        ).lower()

        if node_type in FORBIDDEN_NODE_TYPES:
            result["errors"].append(
                "Forbidden SQL operation detected: "
                f"{node_type.upper()}."
            )

    # -----------------------------------------
    # Load actual extracted DB schema
    # -----------------------------------------

    schema_data = load_schema()

    schema_lookup = build_schema_lookup(
        schema_data
    )

    # -----------------------------------------
    # Detect CTE names
    # -----------------------------------------

    cte_names = {
        cte.alias_or_name.lower()
        for cte in statement.find_all(
            exp.CTE
        )
        if cte.alias_or_name
    }

    # -----------------------------------------
    # Validate tables
    # -----------------------------------------

    alias_lookup = {}

    referenced_physical_tables = []

    for table in statement.find_all(
        exp.Table
    ):
        table_name = table.name

        if not table_name:
            continue

        table_name_lower = (
            table_name.lower()
        )

        # A CTE may appear as a table in the AST.
        # It is not a physical SQL Server table.
        if (
            not table.db
            and table_name_lower in cte_names
        ):
            continue

        schema_name = (
            table.db
            if table.db
            else None
        )

        resolved = resolve_table(
            schema_lookup,
            schema_name,
            table_name,
        )

        if resolved is None:
            if schema_name:
                display_name = (
                    f"{schema_name}.{table_name}"
                )
            else:
                display_name = table_name

            result["errors"].append(
                f"Unknown table: {display_name}."
            )

            continue

        full_name = (
            f"{resolved['schema']}."
            f"{resolved['table']}"
        )

        if (
            full_name
            not in result["referenced_tables"]
        ):
            result[
                "referenced_tables"
            ].append(full_name)

        referenced_physical_tables.append(
            resolved
        )

        alias = (
            table.alias_or_name
            or table_name
        ).lower()

        alias_lookup[alias] = resolved

        # Also allow using the actual table name
        alias_lookup[
            table_name_lower
        ] = resolved

    # -----------------------------------------
    # SELECT aliases
    #
    # Example:
    # SUM(si.Quantity) AS TotalSalesQuantity
    #
    # ORDER BY TotalSalesQuantity
    #
    # TotalSalesQuantity is not a real DB column,
    # so we should not reject it.
    # -----------------------------------------

    select_aliases = {
        alias.alias.lower()
        for alias in statement.find_all(
            exp.Alias
        )
        if alias.alias
    }

    # -----------------------------------------
    # Validate columns
    # -----------------------------------------

    for column in statement.find_all(
        exp.Column
    ):
        column_name = column.name

        if not column_name:
            continue

        column_name_lower = (
            column_name.lower()
        )

        qualifier = (
            column.table.lower()
            if column.table
            else None
        )

        # ORDER BY an alias from SELECT
        if (
            not qualifier
            and column_name_lower
            in select_aliases
        ):
            continue

        # -------------------------------------
        # Qualified column:
        # p.ProductID
        # -------------------------------------

        if qualifier:
            # Could refer to a CTE
            if qualifier in cte_names:
                continue

            table_info = alias_lookup.get(
                qualifier
            )

            if table_info is None:
                result["errors"].append(
                    "Unknown table or alias "
                    f"for column: "
                    f"{qualifier}.{column_name}."
                )

                continue

            if (
                column_name_lower
                not in table_info["columns"]
            ):
                result["errors"].append(
                    f"Unknown column: "
                    f"{qualifier}.{column_name}."
                )

            continue

        # -------------------------------------
        # Unqualified column:
        # Quantity
        # -------------------------------------

        exists = any(
            column_name_lower
            in table_info["columns"]
            for table_info
            in referenced_physical_tables
        )

        if not exists:
            result["errors"].append(
                f"Unknown column: "
                f"{column_name}."
            )

    # -----------------------------------------
    # Remove duplicate errors
    # -----------------------------------------

    result["errors"] = list(
        dict.fromkeys(
            result["errors"]
        )
    )

    # -----------------------------------------
    # Final result
    # -----------------------------------------

    if not result["errors"]:
        result["valid"] = True
        result["status"] = "valid"

    return result